### PR TITLE
Fix potentially insecure use of format strings

### PR DESCRIPTION
**Pull request by ghost**
install-filter can change wait_string, so it may insecure.

### CODE REVIEW

**Comment by ikspress** [comment]
One notable thing is that puts outputs a \n at the end of line, do you think it is good?

**Comment by ikspress** [comment]
Oh, I have a better implement. Please wait. :)

**Comment by tormodvolden** [comment]
Can't you just do `printf("%s", filter_context->wait_string);` ?

**Comment by ikspress** [comment]
> Can't you just do `printf("%s", filter_context->wait_string);` ?

I'm sorry for my late reply. The reason why I use `fputs()` is it is more efficient than `printf()`.

Additionally, I think there should be a better implementation here which don't pause that `stdin` is directed to a file (same as the `pause` in cmd.exe), so please don't merge this PR. I will submit a better implementation some days later.

**Comment by ikspress** [comment]
> Can't you just do `printf("%s", filter_context->wait_string);` ?

I'm sorry for my late reply. The reason why I use `fputs()` is it is more efficient than `printf()`.

Additionally, I think there should be a better implementation here which don't pause that `stdin` is directed to a file (same as the `pause` in cmd.exe), so please don't merge this PR. I will submit a better implementation some days later.

**Pull request closed without merging**
